services:
  traversal-connector:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traversal-connector
    environment:
      - PORT=8080
    ports:
      - "8081:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
