{{- if and (not .Values.controllerTLS.existingSecret) (or .Values.controllerTLS.certPEM .Values.controllerTLS.keyPEM .Values.controllerTLS.caPEM) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traversal-connector.fullname" . }}-controller-tls
  labels:
    {{- include "traversal-connector.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.controllerTLS.certPEM }}
  tls.crt: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.controllerTLS.keyPEM }}
  tls.key: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.controllerTLS.caPEM }}
  ca.crt: {{ . | b64enc }}
  {{- end }}
{{- end -}}
{{- if and (not .Values.upstreamTLS.existingSecret) .Values.upstreamTLS.caPEM }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traversal-connector.fullname" . }}-upstream-tls
  labels:
    {{- include "traversal-connector.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.upstreamTLS.caPEM | b64enc }}
{{- end -}}
