name: dependency-cooldown

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  dependency-cooldown:
    permissions:
      contents: read
      id-token: write
    uses: InteractionLabs/traversal-connector/.github/workflows/dependency-cooldown.yaml@652a775bbd292bad4b4c0b98c53a2c64a4799468 # policy-v1
