name: dependency-policy

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  dependency-policy:
    uses: InteractionLabs/traversal-connector/.github/workflows/reusable-dependency-policy.yml@main # policy-v1
