name: dependency-policy

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  dependency-policy:
    uses: InteractionLabs/traversal-connector/.github/workflows/reusable-dependency-policy.yml@3a4989dc696829c32c091edfa3d872e4a00f7e6c # policy-v1
